### ISSUE TITLE
gawk: cmd. line:25: (FILENAME=- FNR=1) fatal: attempt to use array `a (from span)' in a scalar context when trying to convert colored bash text 

### ISSUE THREAD

**Issue by andrewgtp** [pixelb/scripts#21] opened 2016-07-20 23:26 UTC
This example outputs red bash text using ANSI escape codes but ansi2html errors out when converting to html. Is this supported? Am I using the script wrong?

Output:
`echo -e "\e[0;31mTEST\e[0m" | ansi2html.sh -p`
`gawk: cmd. line:25: (FILENAME=- FNR=1) fatal: attempt to use array `a (from span)' in a scalar context`

**Comment by pixelb** [comment] 2016-07-21 08:12
It works here with GNU Awk 4.1.3 at least.
What version of gawk are you using?
What's the -p option for above?

**Comment by andrewgtp** [comment] 2016-07-21 20:00
Oops ignore the -p but I get same error without the -p. 

I'm using GNU Awk 3.1.5. Looks like this version is not supported with your code.

**Comment by pixelb** [comment] 2016-07-22 12:03
Wow, gawk 3.1.5 was released in 2005!
I think this issue is due to length(array) not being standard awk, though supposedly that feature was added in gawk-3.1.5. Anyway I'll look into making more portable, but you might look at updating to something newer

**Comment by jsarenik** [comment] 2016-07-22 12:35
I can confirm that when I change the way `gawk` is called in `ansi2html.sh` to `gawk --posix` there is the same error even with the latest GNU Awk.

```
diff --git a/scripts/ansi2html.sh b/scripts/ansi2html.sh
index 15719b4..602caa5 100755
--- a/scripts/ansi2html.sh
+++ b/scripts/ansi2html.sh
@@ -307,7 +307,7 @@ s#\x1b(B#\"T0;#g
 s#\x0F#\"T0;#g
 " |
 (
-gawk '
+gawk --posix '
 function dump_line(l,del,c,blanks,ret) {
   for(c=1;c<maxX;c++) {
     if ((c SUBSEP l) in attr || length(cur)) {
```

```
$ echo -e "\e[0;31mTEST\e[0m" | ./ansi2html.sh -p > ahoj.html
gawk: cmd. line:26: (FILENAME=- FNR=1) fatal: length: received array argument
```

**Comment by pixelb** [comment] 2019-11-16 12:55
Pushed in commit 944012c
Thanks!

**Closed by pixelb** 2019-11-16 12:55 UTC
